sonar.projectKey=TsukuyomiKun3_DevOps_Project
sonar.organization=tsukuyomikun3

# Indique à SonarCloud où chercher le code source
sonar.sources=boiteavoisins/backend,boiteavoisins/frontend

# Exclure les dossiers inutiles de l'analyse
sonar.exclusions=**/node_modules/**,**/dist/**